### ISSUE TITLE
关于CJKnumber的错误

### ISSUE THREAD

**Issue by yujunhui** [scnu/scnuthesis#19]
下面是部分的报错信息

> [3] [4] (./thesis.toc
> ! Undefined control sequence.
> <argument> 第\CJKnumber 
>                          {\thecontentslabel }章\quad 
> l.4 ...apter}{\numberline {1}绪论}{1}{chapter.1}

较新版本的xeCJK已经不支持CJKnumber这个option, 
\CJKnumber这个命令被放到了CJKnumb这个包中.

> *************************************************
> * xeCJK warning: "option-deprecated"
> * 
> * The `CJKnumber' option is deprecated.
> * You may load the package `CJKnumb' after xeCJK to use its function.
> * 
> *************************************************

在myscnu.sty中加入
`\RequirePackage{CJKnumb}`
即可解决问题。

**Comment by Z-Donald** [comment]
怎么把hyperref的border去掉, 并且把颜色改成黑色?

**Comment by yujunhui** [comment]
@Z-Donald 
你好，我这边直接xelatex编译是没有出现你说的有border的情况。
heperref宏包中控制border的option是pdfborder，在scnuthesis.cls这个文件中的第81行已经对hyperref做了pdfborder=0 0 1这样的设置了。
