### ISSUE TITLE
bibtex样式文件bstutf8.bst需要更新了

### ISSUE THREAD

**Issue by ghost** [scnu/scnuthesis#20]
bstutf8.bst中设置的bibtex样式文件有一点点不符合要求（期刊名后应该是逗号不是句号）
使用以下压缩包中的bst文件替换即可 https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/buptthesis/buptthesis-v2.0-beta2-ctex.zip

**Comment by Weizhe-Chen** [comment]
@wzpan  好的没问题，感谢你们维护这么优秀的LaTeX模板，若能添加本科生毕业论文就更好了:-)

**Comment by chitolaw** [comment]
我看到现在好像还没有pull request，我就提了个pr

**Comment by jjm2473** [comment]
本科生的模板在这个分支，不过已经多年未更新了 https://github.com/scnu/scnuthesis/tree/bachelor_degree

**Comment by wzpan** [comment]
参见 #26 ，已经合入 PR 。关闭本 issue 。
