### ISSUE TITLE
About fonts problem on overleaf, 关于overleaf中的字体问题

### ISSUE THREAD

**Issue by FrancisYLfan** [scnu/scnuthesis#24]
Hi, I'm a undergraduate of GDUT and will graduate in 2020 summer.
Thanks for your template but when I upload this template on overleaf, I met some problem. It can't be compiled by the engine of overleaf, it doesn't have some CJK fonts, include Source Han Serif SC, Source Han Sans SC.
After some search, I found that it can be replaced by Noto Serif CJK SC, Noto Sans CJK SC, Noto Sans Mono CJK SC and can provide the same effects. So you can just replace the \installOTF command to this:

```LaTeX
\newcommand\installOTF{
	\setmainfont{Times New Roman}
	\setsansfont{Arial}
	\setmonofont{Courier New} 
	\setCJKmainfont{Noto Serif CJK SC}
	\setCJKsansfont{Noto Sans CJK SC}
	\setCJKmonofont{Noto Sans Mono CJK SC}
	\setCJKfamilyfont{song}{Noto Serif CJK SC}
	\setCJKfamilyfont{hei}{Noto Sans Mono CJK SC}
}
```

It's easy that add this info in the README.md doc.
Thanks for your Template.

嗨，我是一名广东工业大学的本科生，将于2020年夏季毕业。
非常感谢您提供模板，但是当我将此模板上传到 overleaf 时，遇到了一些问题。 它无法由下页引擎进行编译，overleaf 不提供某些 CJK 字体，包括 Source Han Serif SC, Source Han Sans SC.
经过一番搜索，我发现可以将其替换为Noto Serif CJK SC，Noto Sans CJK SC，Noto Sans Mono CJK SC, 并且可以保证同样的显示效果。因此，您只需将 \installOTF 命令替换为：

```LaTeX
\newcommand\installOTF{
	\setmainfont{Times New Roman}
	\setsansfont{Arial}
	\setmonofont{Courier New} 
	\setCJKmainfont{Noto Serif CJK SC}
	\setCJKsansfont{Noto Sans CJK SC}
	\setCJKmonofont{Noto Sans Mono CJK SC}
	\setCJKfamilyfont{song}{Noto Serif CJK SC}
	\setCJKfamilyfont{hei}{Noto Sans Mono CJK SC}
}
```

在 README.md 文档中添加一些信息很容易。
感谢您的模板。

**Comment by fuhailin** [comment]
Thanks for your contribution, could you please create a pull request?
感谢你的使用测试，是否可以提出一个 pull request来进行更新？

**Comment by FrancisYLfan** [comment]
No problem.
没问题。
